name: notification_wall
description: A statefull widget to initialize and handle Firebase messaging notifications, using a IndexedStack to keep app state.
version: 1.0.10
homepage: https://github.com/lauro-cesar
repository: https://github.com/sharedway/flutter_notification_wall

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

